# Site Settings
title: "Listen"
description: >
    "Run listening tests in the browser locally or via GitHub pages"
baseurl: ""
url: "https://deeuu.github.io/listen"

github:
    username: "deeuu"
    repository : "listen"
    branch: "gh-pages"

# Build Setting
include: 
    - '_pages'
exclude:
  - package.json
  - node_modules
  - gulpfile.js

kramdown:
  input: GFM
